name = "emendy"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
demosite = ""
tags = ["simple", "minimal", "clean", "fast", "blog", "responsive", "dark mode", "privacy"]
features = ["fast", "blog", "syntax highlighting", "dark mode"]
min_version = "0.41"

[author]
  name = ["Lukas Joswiak", "Emendy"]
  homepage = "https://lukasjoswiak.com"
